### ISSUE TITLE
可以考虑并入 CAP.Extensions 吗？

### ISSUE THREAD

**Issue by maikebing** [lukazh/Lukaz.CAP.ActiveMQ#2]
https://github.com/maikebing/CAP.Extensions

**Comment by tonyqus** [comment]
@maikebing 能不能不要到处捡便宜，我观察你挺久了，就是到处把项目整合起来打个包发package，包括你的所谓NPOI.Plus也是如出一辙。

**Comment by maikebing** [comment]
19年到现在没人维护了， 纳入到一起维护不好吗？检便宜？这有什么便宜？NPOI  ， 只是把常用方法组合到一起， 丰富了功能。 如果这样有问题， 那就不用NPOI了， 难道他是唯一选择吗？

**Comment by maikebing** [comment]
心态好一点吧。
